# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('tutorial', models.CharField(max_length=255)),
                ('priority', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='originalvideo',
            name='video_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.VideoMeta'),
        ),
    ]
