# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalvideo',
            name='priority',
            field=models.IntegerField(blank=True),
        ),
    ]
