# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_auto_20161107_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometa',
            name='youtube_url',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
