# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_auto_20161113_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalvideo',
            name='video_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.VideoMeta'),
        ),
    ]
